charity/charity/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('member.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

charity/member/urls.py
from django.urls import path, include
from member import views
# from django.conf import settings

app_name = 'member'
 


urlpatterns = [
    path('',views.home, name='home'),
    path('go/',views.own_activation,name='go'),
    # path('dashboard/',views.own_activation,name='dashboard'),
    path('dashboard/',views.home12,name='dashboard'),
    path('dashboard/new_user/<int:pk>',views.UserCreateViewDash.as_view(), name='user'),
    path('dashboard/bitcoin_detail/<int:pk>',views.bitcoin_detail, name='bitcoin_detail'),
    path('dashboard/update/<int:pk>',views.UserUpdateViewDash.as_view(), name='update'),
    path('dashboard/downline/<int:pk>',views.downline_member_list, name='downline_team'),
    path('dashboard/sponsor/<int:pk>',views.DirectSponsorTableView.as_view(), name='direct_sponsor_team'),
    path('dashboard/singleline/<int:pk>',views.SingleLineListView.as_view(), name='single_leg'),
    path('dashboard/level_income/<int:pk>', views.level_income, name='level_income'),
    # path('dashboard/transfer_balance', views.transfer_balance,name ='transfer_balance'),
    # path('dashboard/transfer_balance/<int:pk>', views.transfer_balance,name ='transfer_balance'),
    path('dashboard/activate_account/<int:pk>',views.activate_account, name = 'activate_account'),
    path('dashboard/withdrawal_fund/<int:pk>',views.withdrawal_fund, name = 'withdrawal_fund'),
    path('dashboard/reward_income/<int:pk>', views.reward_income, name = 'reward_income'),
    path('dashboard/withdrawal_report/<int:pk>',views.withdrawal_report,name = 'withdrawal_report'),
    path('cripto/',views.web_hook, name='rendaring'),
    path('histry/<int:pk>',views.HistryTableView.as_view(), name='histry'),
    # path('bitcoin/',views.bitcoinpay, name='rendaring'),
    # path('coinbase_webhook/', views.coinbaseWebhook, name="coinbase_webhook"),


#     path('form/',views.RegistrationView.as_view(), name='form_a'),
    # path('update/<int:pk>',views.UpdateViewDash.as_view(), name='update'),
    
#     path('applications/',views.ApplicationListView.as_view(), name='applications'),
    # path('application/',views.UserListTableView.as_view(), name='applicationtable'),
#     path('delete/<int:pk>',views.ApplicationDeleteView.as_view(), name='application_delete'),
#     path('approve/<int:pk>',views.approve_user,name='approve_user'),
#     path('details/<int:pk>',views.ApplicationDetailsView.as_view(), name='details'),
    
    # path('downline/<int:pk>',views.DownlineTeamTableView.as_view(), name='downline_team'),
    # path('sponsor/<int:pk>',views.direct_sponsor, name='direct_sponsor_team'),
    
    # path('singleline/<int:pk>',views.single_line, name='single_leg'),
    
]

charity/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="#">
    <meta name="author" content="#">
    <meta name="keyword" content="#">
    <title>Charity</title>
    <!-- Icons-->
    <link href="{% static 'vendors/@coreui/icons/css/coreui-icons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/flag-icon-css/css/flag-icon.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Main styles for this application-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pace-progress/css/pace.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      // Shared ID
      gtag('config', 'UA-118965717-3');
      // Bootstrap ID
      gtag('config', 'UA-118965717-5');
    </script>
  </head>
  <body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    <header class="app-header navbar">
      <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img class="navbar-brand-full" src="{% static 'img/brand/Asset 2.svg' %}" width="120" height="55" alt="#">
        <img class="navbar-brand-minimized" src="{% static 'img/brand/Asset 2.svg' %}" width="30" height="30" alt="#">
      </a>
      <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--<ul class="nav navbar-nav d-md-down-none">-->
        <!--<li class="nav-item px-3">-->
          <!--<a class="nav-link" href="#">Dashboard</a>-->
        <!--</li>-->
        <!--<li class="nav-item px-3">-->
          <!--<a class="nav-link" href="#">Users</a>-->
        <!--</li>-->
        <!--<li class="nav-item px-3">-->
          <!--<a class="nav-link" href="#">Settings</a>-->
        <!--</li>-->
      <!--</ul>-->
      
          <ul class="nav navbar-nav ml-auto">
              
              {% if user.is_authenticated %}
              
            
              <!-- <li class="nav-item dropdown"> -->
                <!-- <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> -->
          
                  
                    
                  
                <!-- </a> -->
           
                <!-- <div class="dropdown-menu dropdown-menu-right"> -->
                  <!--<div class="dropdown-header text-center">-->
                    <!--<strong>Account</strong>-->
                  <!--</div>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-bell-o"></i> Updates-->
                    <!--<span class="badge badge-info">42</span>-->
                  <!--</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-envelope-o"></i> Messages-->
                    <!--<span class="badge badge-success">42</span>-->
                  <!--</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-tasks"></i> Tasks-->
                    <!--<span class="badge badge-danger">42</span>-->
                  <!--</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-comments"></i> Comments-->
                    <!--<span class="badge badge-warning">42</span>-->
                  <!--</a>-->
                  <!--<div class="dropdown-header text-center">-->
                    <!--<strong>Settings</strong>-->
                  <!--</div>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-user"></i> Profile</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-wrench"></i> Settings</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-usd"></i> Payments-->
                    <!--<span class="badge badge-secondary">42</span>-->
                  <!--</a>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-file"></i> Projects-->
                    <!--<span class="badge badge-primary">42</span>-->
                  <!--</a>-->
                  <!--<div class="dropdown-divider"></div>-->
                  <!--<a class="dropdown-item" href="#">-->
                    <!--<i class="fa fa-shield"></i> Lock Account</a>-->
                  <!-- <a class="dropdown-item" href="#"> -->
                    <!-- <i class="fa fa-user"></i> Profile</a> -->
                  <!-- <a class="dropdown-item" href="{% url 'logout' %}"> -->
                    <!-- <i class="fa fa-lock"></i> Logout</a> -->
                <!-- </div> -->
              <!-- </li> -->
              
              <a class="nav-link" href="{% url 'logout' %}">
                <i class="fa fa-user"></i></a>            
              <li class="nav-item d-md-down-none col-sm-4">                
                  <a class="nav-link" href="{% url 'logout' %}">
                   Logout
                </a>
              </li>
              {% else %}
              <a class="nav-link" href="{% url 'login' %}">
                <i class="fa fa-user"></i></a>
              <li class="nav-item d-md-down-none col-sm-4">                 
                <a class="nav-link" href="{% url 'login' %}">
                   Login
                </a>
              </li>
            
             {% endif %} 
      
      
      </ul>
    </header>

    <div class="app-body">
        
      <div class="sidebar">

          <div class="c-sidebar-brand align-center" align="center">
              <img src="{% static 'img/avatars/user-image.png' %}" alt="userid" width="150px" height="150px">
            
            </div>
            <div class="c-sidebar-brand align-center">
            <p align='center'>{{user.username}}</p>
            </div>
        <nav class="sidebar-nav">
          
          <ul class="nav">
              
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'member:dashboard' %}">
                    <i class="nav-icon icon-speedometer"></i> Dashboard</a>
                </li>
                
              
                <li class="nav-item nav-dropdown">
                  <a class="nav-link nav-dropdown-toggle">
                    <i class="nav-icon icon-credit-card"></i>Profile Manager</a>
                <ul class ="nav-dropdown-items">
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:user' pk=user.pk %}">
                          <i class="nav-icon fa fa-puzzle-piece"></i>New Profile</a>
                      </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:update' pk=user.pk %}">
                          <i class="nav-icon fa fa-puzzle-piece"></i>View / Edit Profile</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:bitcoin_detail' pk=user.pk %}">
                          <i class="nav-icon fa fa-puzzle-piece"></i>Bitcoin Details</a>
                      </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'password_change' %}">
                            <i class="nav-icon icon-credit-card"></i>Change Password</a>
                        </li>
                </ul>  
                </li>
                

                
              <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle">
                  <i class="nav-icon icon-credit-card"></i>My Network</a>
              <ul class ="nav-dropdown-items">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'member:direct_sponsor_team' pk=user.pk %}">
                        <i class="nav-icon fa fa-puzzle-piece"></i>Direct Sponsor</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'member:downline_team' pk=user.pk %}">
                        <i class="nav-icon fa fa-puzzle-piece"></i>Downline Team</a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:single_leg' pk=user.pk %}">
                          <i class="nav-icon icon-credit-card"></i> Single Leg Team</a>
                      </li>
              </ul>  
              </li>
              


              
              <!-- <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle">
                  <i class="nav-icon icon-credit-card"></i>E-Wallet section</a>
              <ul class ="nav-dropdown-items">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'member:level_income' pk=user.pk %}">
                        <i class="nav-icon fa fa-puzzle-piece"></i> Level Income</a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:reward_income' pk=user.pk %}">
                          <i class="nav-icon icon-credit-card"></i> Reward Income</a>
                      </li>
                      

              </ul>
            </li> -->
            

                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle">
                      <i class="nav-icon icon-credit-card"></i>Finance</a>
                  <ul class ="nav-dropdown-items">
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'member:histry' pk=user.pk %}">
                            <i class="nav-icon fa fa-puzzle-piece"></i>Histry</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'member:activate_account' pk=user.pk %}">
                              <i class="nav-icon fa fa-puzzle-piece"></i>Activate Account</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'member:withdrawal_fund' pk=user.pk %}">
                              <i class="nav-icon fa fa-puzzle-piece"></i>Withdrawal Fund</a>
                          </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'member:withdrawal_report' pk=user.pk %}">
                            <i class="nav-icon fa fa-puzzle-piece"></i>Withdrawal Report</a>
                        </li>
                  </ul>  
                  </li>
                
                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle">
                      <i class="nav-icon icon-credit-card"></i>Support</a>
                  <ul class ="nav-dropdown-items">
                      <li class="nav-item">
                          <a class="nav-link" href="#">
                            <i class="nav-icon fa fa-puzzle-piece"></i>Support Ticket</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">
                            <i class="nav-icon fa fa-puzzle-piece"></i>Support Inbox</a>
                        </li>
                  </ul>  
                  </li>
                  
          
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="nav-icon fa fa-cubes"></i> Contuct Us</a>
                </li>


          </ul>
        </nav>
        <button class="sidebar-minimizer brand-minimizer" type="button"></button>
      </div>

      <main class="main">

        <div class="container-fluid">
          <div class="animated fadeIn">

              {% block content %}

              {% endblock %}

          </div>
        </div>
      </main>
    </div>

 
    <footer class="app-footer">
      <div>
        <span>© {% now "Y" %}, All Rights Reserved by Charity.</span>
      </div>
    </footer>
    {% block extra_script %}

    
    {% endblock %}
    <!-- CoreUI and necessary plugins-->
    <script src="{% static 'vendors/jquery/js/jquery.min.js' %}"></script>
    <script src="{% static 'vendors/popper.js/js/popper.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/pace-progress/js/pace.min.js' %}"></script>
    <script src="{% static 'vendors/perfect-scrollbar/js/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'vendors/@coreui/coreui/js/coreui.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

  </body>
</html>

charity/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'front/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'front/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'front/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'front/css/creative.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#">Registration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'member:go' %}">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Your Favorite Source of Free Bootstrap Themes</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

    <section style = "background-color:#3E2723;" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services" style="background-color: #ECEFF1;">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-gem text-primary mb-3 sr-icon-1"></i>
              <h3 class="mb-3">Sturdy Templates</h3>
              <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
              <h3 class="mb-3">Ready to Ship</h3>
              <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
              <h3 class="mb-3">Up to Date</h3>
              <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
              <h3 class="mb-3">Made with Love</h3>
              <p class="text-muted mb-0">You have to make your websites with love these days!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="p-0" id="portfolio">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/1.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/1.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/2.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/2.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/3.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/3.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/4.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/4.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/5.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/5.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'front/img/portfolio/fullsize/6.jpg' %}">
              <img class="img-fluid" src="{% static 'front/img/portfolio/thumbnails/6.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>


    <section id="contact" style ="background-color: #ECEFF1;">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="my-4">
            <p class="mb-5">Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>123-456-6789</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'front/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'front/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'front/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'front/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'front/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'front/js/creative.min.js' %}"></script>

  </body>

</html>