charity/charity/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('member.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

charity/member/urls.py
from django.urls import path, include
from member import views
# from django.conf import settings

app_name = 'member'
 


urlpatterns = [
    path('',views.home, name='home'),
    path('go/',views.own_activation,name='go'),
    # path('dashboard/',views.own_activation,name='dashboard'),
    path('dashboard/',views.home12,name='dashboard'),
    path('dashboard/new_user/<int:pk>',views.UserCreateViewDash.as_view(), name='user'),
    path('dashboard/bitcoin_detail/<int:pk>',views.bitcoin_detail, name='bitcoin_detail'),
    path('dashboard/update/<int:pk>',views.UserUpdateViewDash.as_view(), name='update'),
    path('dashboard/downline/<int:pk>',views.downline_member_list, name='downline_team'),
    path('dashboard/sponsor/<int:pk>',views.DirectSponsorTableView.as_view(), name='direct_sponsor_team'),
    path('dashboard/singleline/<int:pk>',views.SingleLineListView.as_view(), name='single_leg'),
    path('dashboard/level_income/<int:pk>', views.level_income, name='level_income'),
    # path('dashboard/transfer_balance', views.transfer_balance,name ='transfer_balance'),
    # path('dashboard/transfer_balance/<int:pk>', views.transfer_balance,name ='transfer_balance'),
    path('dashboard/activate_account/<int:pk>',views.activate_account, name = 'activate_account'),
    path('dashboard/withdrawal_fund/<int:pk>',views.withdrawal_fund, name = 'withdrawal_fund'),
    path('dashboard/reward_income/<int:pk>', views.reward_income, name = 'reward_income'),
    path('dashboard/withdrawal_report/<int:pk>',views.withdrawal_report,name = 'withdrawal_report'),
    path('cripto/',views.web_hook, name='rendaring'),
    path('histry/<int:pk>',views.HistryTableView.as_view(), name='histry'),
    # path('bitcoin/',views.bitcoinpay, name='rendaring'),
    # path('coinbase_webhook/', views.coinbaseWebhook, name="coinbase_webhook"),


#     path('form/',views.RegistrationView.as_view(), name='form_a'),
    # path('update/<int:pk>',views.UpdateViewDash.as_view(), name='update'),
    
#     path('applications/',views.ApplicationListView.as_view(), name='applications'),
    # path('application/',views.UserListTableView.as_view(), name='applicationtable'),
#     path('delete/<int:pk>',views.ApplicationDeleteView.as_view(), name='application_delete'),
#     path('approve/<int:pk>',views.approve_user,name='approve_user'),
#     path('details/<int:pk>',views.ApplicationDetailsView.as_view(), name='details'),
    
    # path('downline/<int:pk>',views.DownlineTeamTableView.as_view(), name='downline_team'),
    # path('sponsor/<int:pk>',views.direct_sponsor, name='direct_sponsor_team'),
    
    # path('singleline/<int:pk>',views.single_line, name='single_leg'),
    
]

charity/member/forms.py
from django.forms import ModelForm
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User
# from member.models import UserA

# class RegistrationFromA(ModelForm):
#     class Meta:
#         model  = UserA
#         fields = ['first_name','last_name']

class UserProfileInfoForm(ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('phone_number','sponsor','country')

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password')        

class UserFormUpdate(ModelForm):

    class Meta:
        model = User
        fields = ('username','first_name','last_name','email') 


class BalanceTransferForm(forms.Form):
    username = forms.CharField(max_length = 150)
    amount = forms.IntegerField()

class AccoutActivationForm(forms.Form):
    username = forms.CharField(max_length = 150)
    amount = forms.IntegerField()

class WithdrawalFundForm(forms.Form):
    amount = forms.IntegerField() 
    bitcoin_address = forms.CharField(max_length = 200)


class BitcoinDetailForm(forms.Form):
    bitcoin_address = forms.CharField(max_length = 200)
    otp = forms.CharField(max_length = 150)

charity/member/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django_tables2 import SingleTableView 
from .forms import UserProfileInfoForm, UserForm, BalanceTransferForm, AccoutActivationForm ,WithdrawalFundForm, BitcoinDetailForm,UserFormUpdate
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, Activity, create_histry , Histry, WithdrawalHistry
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.contrib.auth.models import User
from .tables import UserInfoTable ,HistryTable
from django.urls import reverse, reverse_lazy
from django.views import generic
import absoluteuri
from datetime import timedelta, datetime
import pytz

utc=pytz.UTC

# # Create your views here.

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import hashlib
from . import md5hash
from django.core.mail import send_mail

# send_mail('Subject here', 'Here is the message.', 'from@example.com', ['to@example.com'], fail_silently=False)





###### redirect -test #####
def return_test(request):
    return redirect('/dashboard/')


@login_required
def own_activation(request):
    user_id = request.user.id
    user_is = get_object_or_404(UserProfileInfo, id=user_id)
    
    if (user_is.user_activation == True) and (user_is.btc_activation == True):
        if user_is.confirm == False:
            user_is.user_confirmation()
        return redirect('/dashboard/') 
    elif (user_is.user_activation == True) and (user_is.btc_activation == False):
        btc_activarion_button(request.user)
        return redirect('/dashboard/')
    elif (user_is.user_activation == False) and (user_is.btc_activation == True):
        btc_activarion_button(request.user)
        return redirect('/dashboard/')
    else:
        btc_activarion_button(request.user)
        return redirect('/dashboard/')
    return None




def user_activitys(self):
    
    user_is = get_object_or_404(UserProfileInfo, user_profile=self.user)
    downline_number = list(UserProfileInfo.objects.filter(application_date__gt = user_is.application_date, confirm=True).order_by('confirmation_date'))
    direct_users =list(UserProfileInfo.objects.filter(confirm = True, sponsor = user_is ).order_by('confirmation_date'))
    obj=len(list(Activity.objects.filter(user=user_is)))
    if len(downline_number)>=2 and len(direct_users)>=1 and obj==0:
        obj = Activity.objects.create()
        obj.level = 1
        obj.user = user_is
        x = downline_number[1]
        date_of_user_20 = x.confirmation_date
        y = direct_users[0]
        date_of_first_user = y.confirmation_date
        if date_of_user_20>date_of_first_user:

            obj.start_date = date_of_user_20                    
        else:
            obj.start_date = date_of_first_user

        # obj.end_date = obj.start_date + timedelta(days=7) 
        obj.end_date = obj.start_date + timedelta(minutes=15)
        obj.save()   
            

    elif len(downline_number)>=4 and len(direct_users)>=2 and obj==1:
        pre_obj=get_object_or_404(Activity, level=1, user=user_is)
        pre_obj_end_date = pre_obj.end_date
        obj = Activity.objects.create()
        obj.level = 2
        obj.user = user_is
        x = downline_number[3]
        date_of_user_40 = x.confirmation_date
        y = direct_users[1]
        date_of_first_user = y.confirmation_date
        if date_of_user_40>date_of_first_user and date_of_user_40>pre_obj_end_date :
            obj.start_date = date_of_user_40
        elif date_of_first_user>date_of_user_40 and date_of_first_user>pre_obj_end_date:
            obj.start_date = date_of_first_user
        else:
            obj.start_date = pre_obj_end_date

        # obj.end_date = obj.start_date + timedelta(days=7) 
        obj.end_date = obj.start_date + timedelta(minutes=45)
        obj.save()
   

    elif len(downline_number)>=6 and len(direct_users)>=3 and obj==2:
        pre_obj=get_object_or_404(Activity, level=2, user=user_is)
        pre_obj_end_date = pre_obj.end_date
        
        obj = Activity.objects.create()
        obj.level = 3
        obj.user = user_is
        x = downline_number[5]
        date_of_user_100 = x.confirmation_date
        y = direct_users[2]
        date_of_first_user = y.confirmation_date
        if date_of_user_100>date_of_first_user and date_of_user_100>pre_obj_end_date :
            obj.start_date = date_of_user_100
        elif date_of_first_user>date_of_user_100 and date_of_first_user>pre_obj_end_date:
            obj.start_date = date_of_first_user
        else:
            obj.start_date = pre_obj_end_date 

        # obj.end_date = obj.start_date + timedelta(days=1) 
        obj.end_date = obj.start_date + timedelta(minutes=45)
        obj.save()

    elif len(downline_number)>=10 and len(direct_users)>=4 and obj==3:
        pre_obj=get_object_or_404(Activity, level=3, user=user_is)
        pre_obj_end_date = pre_obj.end_date

        obj = Activity.objects.create()
        obj.level = 4
        obj.user = user_is
        x = downline_number[9]
        date_of_user_200 = x.confirmation_date
        y = direct_users[3]
        date_of_first_user = y.confirmation_date
        if date_of_user_200>date_of_first_user and date_of_user_200>pre_obj_end_date :
            obj.start_date = date_of_user_200
        elif date_of_first_user>date_of_user_200 and date_of_first_user>pre_obj_end_date:
            obj.start_date = date_of_first_user
        else:
            obj.start_date = pre_obj_end_date

        # obj.end_date = obj.start_date + timedelta(days=7) 
        obj.end_date = obj.start_date + timedelta(minutes=45)
        obj.save()

    elif len(downline_number)>=15 and len(direct_users)>=5 and obj==4:
        pre_obj=get_object_or_404(Activity, level=4, user=user_is)
        pre_obj_end_date = pre_obj.end_date

        obj = Activity.objects.create()
        obj.level = 5
        obj.user = user_is
        x = downline_number[14]
        date_of_user_400 = x.confirmation_date
        y = direct_users[4]
        date_of_first_user = y.confirmation_date
        if date_of_user_400>date_of_first_user and date_of_user_400>pre_obj_end_date :
            obj.start_date = date_of_user_400
        elif date_of_first_user>date_of_user_400 and date_of_first_user>pre_obj_end_date:
            obj.start_date = date_of_first_user
        else:
            obj.start_date = pre_obj_end_date

        # obj.end_date = obj.start_date + timedelta(days = 7)
        obj.end_date = obj.start_date + timedelta(minutes=45)
        obj.save()
    

    elif len(downline_number)>=24 and len(direct_users)>=6 and obj==5:
        pre_obj=get_object_or_404(Activity, level=5, user=user_is)
        pre_obj_end_date = pre_obj.end_date

        obj = Activity.objects.create()
        obj.level = 6
        obj.user = user_is
        x = downline_number[23]
        date_of_user_18000 = x.confirmation_date
        y = direct_users[14]
        date_of_first_user = y.confirmation_date
        if date_of_user_18000>date_of_first_user and date_of_user_18000>pre_obj_end_date :
            obj.start_date = date_of_user_18000
        elif date_of_first_user>date_of_user_18000 and date_of_first_user>pre_obj_end_date:
            obj.start_date = date_of_first_user
        else:
            obj.start_date = pre_obj_end_date

        # obj.end_date = obj.start_date + timedelta(days = 7)
        obj.end_date = obj.start_date + timedelta(minutes=45)
        obj.save()


def point_bonous_reward(user,point):
    user_reward = Histry.objects.filter(user=user).values('reward')
    reward_list_result = [entry for entry in user_reward]
    user_rewards_names=[f['reward'] for f in reward_list_result]
    if point >= 300 and point < 1000:
        reward_name = 'Super Silver'
        if reward_name not in user_rewards_names :
            user.account = user.account + 50
            user.save()
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >= 1000 and point < 3000 ):
        reward_name = 'Glittering Pearl'
        if reward_name not in user_rewards_names :
            user.account = user.account + 150
            user.save()
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >= 3000 and point < 7000 ):
        reward_name = 'Holy Ruby'
        if reward_name not in user_rewards_names :
            user.account = user.account + 300
            user.save()
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >=7000 and point <15000):
        reward_name = 'Extreme Gold'
        if reward_name not in user_rewards_names :
            user.account = user.account + 500
            user.save()
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >= 15000 and point<40000 ):
        reward_name = 'Premium Platinum'
        if reward_name not in user_rewards_names :
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >=40000 and point < 80000 ):
        reward_name = 'Reflective Rhodium'
        if reward_name not in user_rewards_names :
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    elif(point >=80000):
        reward_name = 'Sharp Diamond'
        if reward_name not in user_rewards_names :
            create_histry(user=user,reward=reward_name, rewarded_date=utc.localize(datetime.now())) 
    # elif(point ==800):
    #     reward_name = 'Lustrous Taitenium'
    #     if reward_name not in user_rewards_names :

charity/member/templates/actibation_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>please activate your account using btc and user payment</h1>
        <div>
                <a class="buy-with-crypto" data-cache-disabled="true" data-custom="MY_CUSTOM_DATA"
                   href="https://commerce.coinbase.com/checkout/83f2f635-8bc7-474a-b9b5-1b72317308ae">
                  <span>Buy with Crypto</span>
                </a>
                <script src="https://commerce.coinbase.com/v1/checkout.js?version=201807">
                </script>
              </div>
    
</body>
</html>

charity/member/templates/application_lists.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load widget_tweaks %}
{% block content %}

{% render_table table %}

{% endblock %}

charity/member/templates/bitcoin_detail.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card mx-4 mt-4">
            <div class="card-body p-4">
              <h3 class="pb-4 text-center">Bitcoin Detail</h3>
              <h4 class="pb-4 text-center">User is {{ user.username }}</h4>
            
            <form method="POST">
                    {% csrf_token %}

             <div class="input-group mb-3">
              <label for="{{ form.bitcoin_address.id_for_label }}"><strong>{{ form.bitcoin_address.label }}</strong></label>
              {% render_field form.bitcoin_address class="form-control w-100" placeholder='bitcoin_address' %}
              {% for error in form.bitcoin_address.errors %}
              <div class="text-danger">{{ error }}</div>
            {% endfor %}
           </div>
           <div class="input-group mb-3">
            <label for="{{ form.otp.id_for_label }}"><strong>{{ form.otp.label }}</strong></label>
            {% render_field form.otp class="form-control w-100" placeholder='otp' %}
            {% for error in form.otp.errors %}
            <div class="text-danger">{{ error }}</div>
          {% endfor %}
         </div>

         <button class="btn btn-block btn-success mt-4" type="">Get Otp</button>
                    <button class="btn btn-block btn-success mt-4" type="submit">Submit</button>
            </form>
            </div>
          </div>
        </div>
      </div>

{% endblock %}      

charity/member/templates/index_dash.html
{% extends 'base.html' %}


{% block content %}


            <div class="row mt-4">
              <div class="col-sm-6 col-lg-3">
                <div class="card text-white bg-primary">
                  <div class="card-body pb-0">
                    <div class="btn-group float-right">
                      <!-- <button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        <!-- <i class="icon-settings"></i> -->
                      <!-- </button> -->
                    
                        <!-- <div class="dropdown-menu dropdown-menu-right"> -->
                          <!-- <a class="dropdown-item" href="#">All Members</a> -->
                        <!-- </div> -->
                  
                    </div>                    
                    <div>Single Leg Downline</div>
                    <div class="text-value"></div>
                  </div>
                  <div class="chart-wrapper mt-3 mx-3" style="height:70px;"><h1>{{ single_leg }}</h1>
                    <!-- <canvas class="chart" id="card-chart1" height="70"></canvas> -->
                  </div>
                </div>
              </div>
              <!-- /.col-->
                <div class="col-sm-6 col-lg-3">
                <div class="card text-white bg-info">
                  <div class="card-body pb-0">
                    <div class="btn-group float-right">
                      <!-- <button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        <!-- <i class="icon-settings"></i> -->
                      <!-- </button> -->
                    
                      <!-- <div class="dropdown-menu dropdown-menu-right"> -->
                        
                          <!-- <a class="dropdown-item" href="#">All Application</a> -->
                      
            
                          <!-- <a class="dropdown-item" href="#">Add Application</a> -->
                      
                      <!-- </div>                   -->
                    </div>                   
                    <div>Lavel Income</div>
                    <div class="text-value"></div>
                  </div>
                  <div class="chart-wrapper mt-3" style="height:70px;"><h1>&nbsp;&nbsp;{{ income }}</h1>
                    <canvas class="chart" id="card-chart2" height="70"></canvas>
                  </div>
                </div>
              </div>
              <!-- /.col-->
              <div class="col-sm-6 col-lg-3">
                <div class="card text-white bg-warning"> 
                  <div class="card-body pb-0">
                    <div class="btn-group float-right">
                      <!-- <button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        <!-- <i class="icon-settings"></i> -->
                      <!-- </button> -->
                  
                        <!-- <div class="dropdown-menu dropdown-menu-right"> -->
                          
                            <!-- <a class="dropdown-item" href="#">All Donations</a> -->
                          
                            <!-- <a class="dropdown-item" href="#">Add Donation</a> -->
                          
                        <!-- </div> -->
                      
                    </div>
                    <div>Total Earnings</div>
                    <div class="text-value"></div>
                  </div>
                  <div class="chart-wrapper mt-3" style="height:70px;"><h1>&nbsp;&nbsp;{{ total_income }} </h1>
                    <canvas class="chart" id="card-chart3" height="70"></canvas>
                  </div>
                </div>
              </div>
              <!-- /.col-->
              <div class="col-sm-6 col-lg-3">
                <div class="card text-white bg-danger">
                  <div class="card-body pb-0">
                    <div class="btn-group float-right">
                      <!-- <button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        <!-- <i class="icon-settings"></i> -->
                      <!-- </button> -->
                      
                        <!-- <div class="dropdown-menu dropdown-menu-right"> -->
                        
                            <!-- <a class="dropdown-item" href="#">All Investments</a> -->
                        
                          
                            <!-- <a class="dropdown-item" href="#">Add Investment</a> -->
                        
                        <!-- </div> -->
                    
                    </div>                   
                    <div>Rewards Points</div>
                    <div class="text-value"></div>
                  </div>
                  <div class="chart-wrapper mt-3 mx-3" style="height:70px;"><h1>{{ points }}</h1>
                    <canvas class="chart" id="card-chart4" height="70"></canvas>
                  </div>
                </div>
              </div>
              <!-- /.col-->
            </div>

            <!-- /.row-->


            <!-- Target -->
<!-- The text field -->
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Referral URL</span>
  </div>
  <input type="text" class="form-control" {% if user.userprofileinfo.confirm and user.is_authenticated %} value="{{ referral_url }}" id="myInput" placeholder="{{ referral_url }}" {% endif %} >
</div>

<button onclick="myFunction()">Copy URL</button>

{% if user.userprofileinfo.confirm and user.is_authenticated %}
{% else %}


{% if user.userprofileinfo.user_activation == None and user.userprofileinfo.btc_activation %}

<header class="app-header navbar">
  <h1><p align="center">activate your account with user</p></h1>	
  
</header>
{% elif user.userprofileinfo.btc_activation == None and user.userprofileinfo.user_activation %}
<header class="app-header navbar">
    <h1><p align="center"><a href="{% url 'member:rendaring' %}">activate your account with btc</a></p></h1>	
    
  </header>
{% endif %}
<header class="app-header navbar">
    <h1><p align="center"><a href="{% url 'member:rendaring' %}">activate your account with btc & any user</a></p></h1>	
    
  </header>
{% endif %}

{% if user.userprofileinfo.confirm %}


{% endif %}


                
<h3 class="text-center text-black">Accounting Level Activity</h3>
<br>

<div class="container">
<div class="bs-example">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>levels</th>
                <th>GlobalDownline</th>
                <th>Expected Direct <br> Member</th>
                <th>Actual Direct <br> Member</th>
				<th>income</th>
				<th>Achive <br> Date</th>
				<th>Release <br>date</th>
				<th>Status</th>
				
            </tr>
        </thead>
        <tbody>

          
            <tr>
                <td>1</td>
                <td>2 </td>
                <td>1</td>
                <td>1</td>
        <td>10.00</td>
				<td>          {% for activity in user_activity %}
                    {% if activity.level == 1 %}
            {{ activity.start_date }}
            {% endif %}
            {% endfor %}</td>
				<td>          {% for activity in user_activity %}
            {% if activity.level == 1 %}
        {{ activity.end_date }}
        {% endif %}
        {% endfor %}</td>
				<td>           {% for activity in user_activity %}
            {% if activity.level == 1 %}
         {{ activity.level_status }}
          {% endif %}
          {% endfor %}</td>
        
            </tr>
            
            <tr>
                <td>2</td>
                <td>4</td>
                <td>2</td>
                <td>1</td>
        <td>20.00</td>
				<td>         {% for activity in user_activity %}
            {% if activity.level == 2 %}
    {{ activity.start_date }}
    {% endif %}
    {% endfor %}</td>
				<td>         {% for activity in user_activity %}
            {% if activity.level == 2 %}
    {{ activity.end_date }}
    {% endif %}
    {% endfor %}</td>
        <td>         {% for activity in user_activity %}
            {% if activity.level == 2 %}
    {{ activity.level_status }}
    {% endif %}
    {% endfor %}</td>
        
            </tr>
            <tr>
                <td>3</td>
                <td>6</td>
                <td>3</td>
                <td>1</td>
        <td>40.00</td>
        
				<td>          {% for activity in user_activity %}
            {% if activity.level == 3 %}
    {{ activity.start_date }}
    {% endif %}
    {% endfor %}</td>
				<td>          {% for activity in user_activity %}
            {% if activity.level == 3 %}
    {{ activity.end_date }}
    {% endif %}
    {% endfor %}</td>
        <td>         {% for activity in user_activity %}
            {% if activity.level == 3 %}
    {{ activity.level_status }}
    {% endif %}
    {% endfor %}</td>
        
            </tr>   
				<tr>
                <td>4</td>
                <td>10</td>
                <td>4</td>
                <td>1</td>
        <td>80.00</td>
        
				<td>          {% for activity in user_activity %}
            {% if activity.level == 4 %}
    {{ activity.start_date }}
    {% endif %}
    {% endfor %}</td>
				<td>         {% for activity in user_activity %}
            {% if activity.level == 4 %}
    {{ activity.end_date }}
    {% endif %}
    {% endfor %}</td>
        <td>          {% for activity in user_activity %}
            {% if activity.level == 4 %}
    {{ activity.level_status }}
    {% endif %}
    {% endfor %}</td>
        
            </tr> 
            <tr>
                <td>5</td>
                <td>15</td>
                <td>5</td>
                <td>1</td>
        <td>150.00</td>
        
				<td>          {% for activity in user_activity %}
            {% if activity.level == 5 %}
    {{ activity.start_date }}
    {% endif %}
    {% endfor %}</td>
				<td>          {% for activity in user_activity %}
            {% if activity.level == 5 %}
    {{ activity.end_date }}
    {% endif %}
    {% endfor %}</td>
        <td>          {% for activity in user_activity %}
            {% if activity.level == 5 %}
    {{ activity.level_status }}
    {% endif %}
    {% endfor %}</td>
        
            </tr> 
            <tr>
                <td>6</td>
                <td>24</td>
                <td>6</td>
                <td>1</td>
        <td>200.00</td>
        
				<td> {% for activity in user_activity %}
          {% if activity.level == 5 %}
  {{ activity.start_date }}
  {% endif %}
  {% endfor %}</td>
				<td>{% for activity in user_activity %}
          {% if activity.level == 5 %}
  {{ activity.end_date }}
  {% endif %}
  {% endfor %}</td>
        <td>{% for activity in user_activity %}
          {% if activity.level == 5 %}
  {{ activity.level_status }}
  {% endif %}
  {% endfor %}</td>
        
            </tr> 
        </tbody>
    </table>
</div>
</div> 
 
 

{% endblock %}


{% block extra_script %}

<script>
  
function myFunction() {
  var copyText = document.getElementById("myInput");
  copyText.select();
  copyText.setSelectionRange(0, 99999)
  document.execCommand("copy");
  alert("Copied the text: " + copyText.value);
}
</script>

{% endblock %}

charity/member/templates/reward_income.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>sorry, you have no reward income</h1>
</body>
</html>

charity/member/templates/user_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block content %}

{% for user in users %}
{{ user.user.username }}<br />


{% endfor %}
{{number}}
{% endblock %}